export const THEME = {
  DARK: 'dark',
  LIGHT: 'light',
}

export const LOCAL_STORAGE_SHELVES_KEY = 'shelves'

export const GOOGLE_BOOKS_API_URL = `https://www.googleapis.com/books/v1/`

export const CATEGORIES = [
  { id: 1, name: 'ANTIQUES & COLLECTIBLES' },
  { id: 2, name: 'ARCHITECTURE' },
  { id: 3, name: 'ART' },
  { id: 4, name: 'BIBLES' },
  { id: 5, name: 'BIOGRAPHY & AUTOBIOGRAPHY' },
  { id: 6, name: 'BODY, MIND & SPIRIT' },
  { id: 7, name: 'BUSINESS & ECONOMICS' },
  { id: 8, name: 'COMICS & GRAPHIC NOVELS' },
  { id: 9, name: 'COMPUTERS' },
  { id: 10, name: 'COOKING' },
  { id: 11, name: 'CRAFTS & HOBBIES' },
  { id: 12, name: 'DESIGN' },
  { id: 13, name: 'DRAMA' },
  { id: 14, name: 'EDUCATION' },
  { id: 15, name: 'FAMILY & RELATIONSHIPS' },
  { id: 16, name: 'FICTION' },
  { id: 17, name: 'FOREIGN LANGUAGE STUDY' },
  { id: 18, name: 'GAMES & ACTIVITIES' },
  { id: 19, name: 'GARDENING ' },
  { id: 20, name: 'HEALTH & FITNESS' },
  { id: 21, name: 'HISTORY' },
  { id: 22, name: 'HOUSE & HOME' },
  { id: 23, name: 'HUMOR' },
  { id: 24, name: 'JUVENILE FICTION' },
  { id: 25, name: 'JUVENILE NONFICTION' },
  { id: 26, name: 'LANGUAGE ARTS & DISCIPLINES' },
  { id: 27, name: 'LAW' },
  { id: 28, name: 'LITERARY COLLECTIONS' },
  { id: 29, name: 'LITERARY CRITICISM' },
  { id: 30, name: 'MATHEMATICS' },
  { id: 31, name: 'MEDICAL' },
  { id: 32, name: 'MUSIC' },
  { id: 33, name: 'NATURE' },
  { id: 34, name: 'PERFORMING ARTS' },
  { id: 35, name: 'PETS' },
  { id: 36, name: 'PHILOSOPHY ' },
  { id: 37, name: 'PHOTOGRAPHY' },
  { id: 38, name: 'POETRY' },
  { id: 39, name: 'POLITICAL SCIENCE' },
  { id: 40, name: 'PSYCHOLOGY' },
  { id: 41, name: 'REFERENCE' },
  { id: 42, name: 'RELIGION' },
  { id: 43, name: 'SCIENCE' },
  { id: 44, name: 'SELF-HELP' },
  { id: 45, name: 'SOCIAL SCIENCE' },
  { id: 46, name: 'SPORTS & RECREATION' },
  { id: 47, name: 'STUDY AIDS' },
  { id: 48, name: 'TECHNOLOGY & ENGINEERING' },
  { id: 49, name: 'TRANSPORTATION' },
  { id: 50, name: 'TRAVEL' },
  { id: 51, name: 'TRUE CRIME' },
  { id: 52, name: 'YOUNG ADULT FICTION' },
  { id: 53, name: 'YOUNG' },
]
